split performance test into http low get and post as two different jobs

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -2,14 +2,15 @@ workflows:
   version: 2
   unittest:
     jobs:
-      - unit
-      - metrics
+     # - unit
+     # - metrics
   integrationtest:
     jobs:
-      - integration
+     # - integration
   performancetest:
     jobs:
-      - performanceHttpLow
+      - performanceHttpLowGet
+      - performanceHttpLowPost
 
 jobs:
   unit:
@@ -437,7 +438,7 @@ jobs:
             echo "tls high performance test ${errwrite4} write errors"
 
 
-  performanceHttpLow:
+  performanceHttpLowGet:
     docker:
       - image: simonmittag/wrk:go1.16
     resource_class: xlarge
@@ -518,6 +519,98 @@ jobs:
       - store_artifacts:
           path: performance/performance_results_http_low_get.json
           destination: performance_results_http_low_get.json
+
+  performanceHttpLowPost:
+    docker:
+      - image: simonmittag/wrk:go1.16
+    resource_class: xlarge
+    environment:
+      LOGLEVEL: WARN
+      LOGCOLOR: FALSE
+      UPSTREAM_ONE_PORT: 60083
+      UPSTREAM_ONE_SLUG: /mse6
+      UPSTREAM_TWO_PORT: 60084
+      UPSTREAM_TWO_SLUG: /mse6
+      UPSTREAM_THREE_PORT: 60085
+      UPSTREAM_THREE_SLUG: /s1
+      J8A_ONE_PORT: 8080
+      J8A_ONE_CFG: ./integration/j8a1.yml
+      TEST_DURATION_SECONDS: 10
+      TEST_CONCURRENCY_LOW: 12
+      TEST_CONCURRENCY_LOW_THRESHOLD: 1400
+      TEST_STATUS_ERRORS_THRESHOLD: 10
+    steps:
+      - checkout
+      - run:
+          name: Install deps
+          command: |
+            sudo apt-get install jq
+            go get github.com/simonmittag/pwt
+            go install github.com/simonmittag/pwt/cmd/pwt
+            go get github.com/simonmittag/mse6
+            go install github.com/simonmittag/mse6/cmd/mse6
+      - run:
+          name: Start upstream server one
+          command: mse6 -p ${UPSTREAM_ONE_PORT}
+          background: true
+      - run:
+          name: Wait for upstream server one
+          command: pwt localhost:${UPSTREAM_ONE_PORT}
+      - run:
+          name: Start upstream server two
+          command: mse6 -p ${UPSTREAM_TWO_PORT}
+          background: true
+      - run:
+          name: Wait for upstream server two
+          command: pwt localhost:${UPSTREAM_TWO_PORT}
+      - run:
+          name: Start upstream server three
+          command: mse6 -p ${UPSTREAM_THREE_PORT} -u ${UPSTREAM_THREE_SLUG}
+          background: true
+      - run:
+          name: Wait for upstream server three
+          command: pwt localhost:${UPSTREAM_THREE_PORT}
+      - run:
+          name: Install j8a
+          command: |
+            go build github.com/simonmittag/j8a
+            go install github.com/simonmittag/j8a/cmd/j8a
+      - run:
+          name: Start j8a one
+          command: LOGLEVEL=WARN j8a -c ${J8A_ONE_CFG}
+          background: true
+      - run:
+          name: Wait for j8a one
+          command: pwt localhost:${J8A_ONE_PORT}
+
+      - run:
+          name: Execute concurrency ${TEST_CONCURRENCY_LOW} POST performance tests in HTTP mode
+          command: cd performance && wrk -t ${TEST_CONCURRENCY_LOW} -c ${TEST_CONCURRENCY_LOW} -d ${TEST_DURATION_SECONDS}s -s post.lua -- http://localhost:${J8A_ONE_PORT}/mse6/post performance_results_http_low_post.json
+      - run:
+          name: Check concurrency ${TEST_CONCURRENCY_LOW} POST performance tests in HTTP mode
+          command: |
+            export reqss=`cat performance/performance_results_http_low_post.json | jq .requestspersecond`
+            test ${reqss} -gt ${TEST_CONCURRENCY_LOW_THRESHOLD} && (echo "performance test passed, ${reqss} req/s > ${TEST_CONCURRENCY_LOW_THRESHOLD} req/s";exit 0) || (echo "performance test failed, ${reqss} req/s < ${TEST_CONCURRENCY_LOW_THRESHOLD} req/s";pkill jq)
+            export errstatus=`cat performance/performance_results_http_low_post.json | jq .errors.status`
+            test ${errstatus} -lt ${TEST_STATUS_ERRORS_THRESHOLD} && (echo "performance test passed, ${errstatus} status errors";exit 0) || (echo "performance test failed, ${errstatus} status errors";pkill jq)
+            export errtimeout=`cat performance/performance_results_http_low_post.json | jq .errors.timeout`
+            test ${errtimeout} -lt ${TEST_STATUS_ERRORS_THRESHOLD} && (echo "performance test passed, ${errtimeout} timeout errors";exit 0) || (echo "performance test failed, ${errtimeout} timeout errors";pkill jq)
+            export errconnect=`cat performance/performance_results_http_low_post.json | jq .errors.connect`
+            test ${errconnect} -lt ${TEST_STATUS_ERRORS_THRESHOLD} && (echo "performance test passed, ${errconnect} connect errors";exit 0) || (echo "performance test failed, ${errconnect} connect errors";pkill jq)
+            export errread=`cat performance/performance_results_http_low_post.json | jq .errors.read`
+            test ${errread} -lt ${TEST_STATUS_ERRORS_THRESHOLD} && (echo "performance test passed, ${errread} read errors";exit 0) || (echo "performance test failed, ${errread} read errors";pkill jq)
+            export errwrite=`cat performance/performance_results_http_low_post.json | jq .errors.write`
+            test ${errwrite} -lt ${TEST_STATUS_ERRORS_THRESHOLD} && (echo "performance test passed, ${errwrite} write errors";exit 0) || (echo "performance test failed, ${errwrite} write errors";pkill jq)
+
+      - run:
+          name: Display performance test results
+          command: |
+            export reqsshlp=`cat performance/performance_results_http_low_post.json | jq .requestspersecond`
+            echo "=> performance test results HTTP POST 2.5kb, concurrency ${TEST_CONCURRENCY_LOW}, ${reqsshlp} req/s"
+      - store_artifacts:
+          path: performance/performance_results_http_low_post.json
+          destination: performance_results_http_low_post.json
+
 
   performance:
     docker:
