moved store artifacts jobs to back of workflow

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -446,32 +446,44 @@ jobs:
           name: Wait for j8a three
           command: pwt localhost:${J8A_THREE_PORT}
       - run:
-          name: Execute concurrency ${TEST_CONCURRENCY_LOW} performance tests in HTTP mode
-          command: cd performance && wrk -t ${TEST_CONCURRENCY_LOW} -c ${TEST_CONCURRENCY_LOW} -d ${TEST_DURATION_SECONDS}s -s post.lua -- http://localhost:${J8A_ONE_PORT}/mse6/post performance_results_http_low.json
-      - store_artifacts:
-          path: performance/performance_results_http_low.json
-          destination: performance_results_http_low.json
+          name: Execute concurrency ${TEST_CONCURRENCY_LOW} GET performance tests in HTTP mode
+          command: cd performance && wrk -t ${TEST_CONCURRENCY_LOW} -c ${TEST_CONCURRENCY_LOW} -d ${TEST_DURATION_SECONDS}s -s get.lua -- http://localhost:${J8A_ONE_PORT}/mse6/post performance_results_http_low_get.json
       - run:
-          name: Check concurrency ${TEST_CONCURRENCY_LOW} performance tests in HTTP mode
+          name: Check concurrency ${TEST_CONCURRENCY_LOW} GET performance tests in HTTP mode
           command: |
-            export reqss=`cat performance/performance_results_http_low.json | jq .requestspersecond`
+            export reqss=`cat performance/performance_results_http_low_get.json | jq .requestspersecond`
             test ${reqss} -gt ${TEST_CONCURRENCY_LOW_THRESHOLD} && (echo "performance test passed, ${reqss} req/s > ${TEST_CONCURRENCY_LOW_THRESHOLD} req/s";exit 0) || (echo "performance test failed, ${reqss} req/s < ${TEST_CONCURRENCY_LOW_THRESHOLD} req/s";pkill jq)
-            export errstatus=`cat performance/performance_results_http_low.json | jq .errors.status`
+            export errstatus=`cat performance/performance_results_http_low_get.json | jq .errors.status`
             test ${errstatus} -eq 0 && (echo "performance test passed, ${errstatus} status errors";exit 0) || (echo "performance test failed, ${errstatus} status errors";pkill jq)
-            export errtimeout=`cat performance/performance_results_http_low.json | jq .errors.timeout`
+            export errtimeout=`cat performance/performance_results_http_low_get.json | jq .errors.timeout`
             test ${errtimeout} -eq 0 && (echo "performance test passed, ${errtimeout} timeout errors";exit 0) || (echo "performance test failed, ${errtimeout} timeout errors";pkill jq)
-            export errconnect=`cat performance/performance_results_http_low.json | jq .errors.connect`
+            export errconnect=`cat performance/performance_results_http_low_get.json | jq .errors.connect`
             test ${errconnect} -eq 0 && (echo "performance test passed, ${errconnect} connect errors";exit 0) || (echo "performance test failed, ${errconnect} connect errors";pkill jq)
-            export errread=`cat performance/performance_results_http_low.json | jq .errors.read`
+            export errread=`cat performance/performance_results_http_low_get.json | jq .errors.read`
             test ${errread} -eq 0 && (echo "performance test passed, ${errread} read errors";exit 0) || (echo "performance test failed, ${errread} read errors";pkill jq)
-            export errwrite=`cat performance/performance_results_http_low.json | jq .errors.write`
+            export errwrite=`cat performance/performance_results_http_low_get.json | jq .errors.write`
+            test ${errwrite} -eq 0 && (echo "performance test passed, ${errwrite} write errors";exit 0) || (echo "performance test failed, ${errwrite} write errors";pkill jq)
+      - run:
+          name: Execute concurrency ${TEST_CONCURRENCY_LOW} POST performance tests in HTTP mode
+          command: cd performance && wrk -t ${TEST_CONCURRENCY_LOW} -c ${TEST_CONCURRENCY_LOW} -d ${TEST_DURATION_SECONDS}s -s post.lua -- http://localhost:${J8A_ONE_PORT}/mse6/post performance_results_http_low_post.json
+      - run:
+          name: Check concurrency ${TEST_CONCURRENCY_LOW} POST performance tests in HTTP mode
+          command: |
+            export reqss=`cat performance/performance_results_http_low_post.json | jq .requestspersecond`
+            test ${reqss} -gt ${TEST_CONCURRENCY_LOW_THRESHOLD} && (echo "performance test passed, ${reqss} req/s > ${TEST_CONCURRENCY_LOW_THRESHOLD} req/s";exit 0) || (echo "performance test failed, ${reqss} req/s < ${TEST_CONCURRENCY_LOW_THRESHOLD} req/s";pkill jq)
+            export errstatus=`cat performance/performance_results_http_low_post.json | jq .errors.status`
+            test ${errstatus} -eq 0 && (echo "performance test passed, ${errstatus} status errors";exit 0) || (echo "performance test failed, ${errstatus} status errors";pkill jq)
+            export errtimeout=`cat performance/performance_results_http_low_post.json | jq .errors.timeout`
+            test ${errtimeout} -eq 0 && (echo "performance test passed, ${errtimeout} timeout errors";exit 0) || (echo "performance test failed, ${errtimeout} timeout errors";pkill jq)
+            export errconnect=`cat performance/performance_results_http_low_post.json | jq .errors.connect`
+            test ${errconnect} -eq 0 && (echo "performance test passed, ${errconnect} connect errors";exit 0) || (echo "performance test failed, ${errconnect} connect errors";pkill jq)
+            export errread=`cat performance/performance_results_http_low_post.json | jq .errors.read`
+            test ${errread} -eq 0 && (echo "performance test passed, ${errread} read errors";exit 0) || (echo "performance test failed, ${errread} read errors";pkill jq)
+            export errwrite=`cat performance/performance_results_http_low_post.json | jq .errors.write`
             test ${errwrite} -eq 0 && (echo "performance test passed, ${errwrite} write errors";exit 0) || (echo "performance test failed, ${errwrite} write errors";pkill jq)
       - run:
           name: Execute concurrency ${TEST_CONCURRENCY_JWT_LOW} JWT performance tests in HTTP mode
           command: cd performance && wrk -t ${TEST_CONCURRENCY_JWT_LOW} -c ${TEST_CONCURRENCY_JWT_LOW} -d ${TEST_DURATION_SECONDS}s -s postJwt.lua -- http://localhost:${J8A_ONE_PORT}/jwtrs256/post performance_results_jwt_http_low.json
-      - store_artifacts:
-          path: performance/performance_results_jwt_http_low.json
-          destination: performance_results_jwt_http_low.json
       - run:
           name: Check concurrency ${TEST_CONCURRENCY_JWT_LOW} JWT performance tests in HTTP mode
           command: |
@@ -490,9 +502,6 @@ jobs:
       - run:
           name: Execute concurrency ${TEST_CONCURRENCY_LOW} performance tests in TLS mode
           command: cd performance && wrk -t ${TEST_CONCURRENCY_LOW} -c ${TEST_CONCURRENCY_LOW} -d ${TEST_DURATION_SECONDS}s -s post.lua -- https://localhost:${J8A_THREE_PORT}/mse6/post performance_results_tls_low.json
-      - store_artifacts:
-          path: performance/performance_results_tls_low.json
-          destination: performance_results_tls_low.json
       - run:
           name: Check concurrency ${TEST_CONCURRENCY_LOW} performance tests in TLS mode
           command: |
@@ -511,9 +520,6 @@ jobs:
       - run:
           name: Execute concurrency ${TEST_CONCURRENCY_HIGH} performance tests in HTTP mode
           command: cd performance && wrk -t ${TEST_CONCURRENCY_HIGH} -c ${TEST_CONCURRENCY_HIGH} -d ${TEST_DURATION_SECONDS}s -s post.lua -- http://localhost:${J8A_ONE_PORT}/mse6/post performance_results_http_high.json
-      - store_artifacts:
-          path: performance/performance_results_http_high.json
-          destination: performance_results_http_high.json
       - run:
           name: Check concurrency ${TEST_CONCURRENCY_HIGH} performance tests in HTTP mode
           command: |
@@ -532,9 +538,6 @@ jobs:
       - run:
           name: Execute concurrency ${TEST_CONCURRENCY_HIGH} performance tests in TLS mode
           command: cd performance && wrk -t ${TEST_CONCURRENCY_HIGH} -c ${TEST_CONCURRENCY_HIGH} -d ${TEST_DURATION_SECONDS}s -s post.lua -- https://localhost:${J8A_THREE_PORT}/mse6/post performance_results_tls_high.json
-      - store_artifacts:
-          path: performance/performance_results_tls_high.json
-          destination: performance_results_tls_high.json
       - run:
           name: Check concurrency ${TEST_CONCURRENCY_HIGH} performance tests in TLS mode
           command: |
@@ -553,8 +556,10 @@ jobs:
       - run:
           name: Display performance test results
           command: |
-            export reqsshl=`cat performance/performance_results_http_low.json | jq .requestspersecond`
-            echo "=> performance test results HTTP POST 2.5kb, concurrency ${TEST_CONCURRENCY_LOW}, ${reqsshl} req/s"
+            export reqsshlg=`cat performance/performance_results_http_low_get.json | jq .requestspersecond`
+            echo "=> performance test results HTTP GET, concurrency ${TEST_CONCURRENCY_LOW}, ${reqsshlg} req/s"
+            export reqsshlp=`cat performance/performance_results_http_low_post.json | jq .requestspersecond`
+            echo "=> performance test results HTTP POST 2.5kb, concurrency ${TEST_CONCURRENCY_LOW}, ${reqsshlp} req/s"
             export reqsshjl=`cat performance/performance_results_jwt_http_low.json | jq .requestspersecond`
             echo "=> performance test results HTTP POST 2.5kb (JWT), concurrency ${TEST_CONCURRENCY_JWT_LOW}, ${reqsshjl} req/s"
             export reqsshh=`cat performance/performance_results_http_high.json | jq .requestspersecond`
@@ -563,3 +568,21 @@ jobs:
             echo "=> performance test results TLS POST 2.5kb, concurrency ${TEST_CONCURRENCY_LOW}, ${reqsstl} req/s"
             export reqssth=`cat performance/performance_results_tls_high.json | jq .requestspersecond`
             echo "=> performance test results TLS POST 2.5kb, concurrency ${TEST_CONCURRENCY_HIGH}, ${reqssth} req/s"
+      - store_artifacts:
+          path: performance/performance_results_http_low_get.json
+          destination: performance_results_http_low_get.json
+      - store_artifacts:
+          path: performance/performance_results_http_low_post.json
+          destination: performance_results_http_low_post.json
+      - store_artifacts:
+          path: performance/performance_results_jwt_http_low.json
+          destination: performance_results_jwt_http_low.json
+      - store_artifacts:
+          path: performance/performance_results_tls_low.json
+          destination: performance_results_tls_low.json
+      - store_artifacts:
+          path: performance/performance_results_http_high.json
+          destination: performance_results_http_high.json
+      - store_artifacts:
+          path: performance/performance_results_tls_high.json
+          destination: performance_results_tls_high.json
